name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.13.2
            
      - name: Deno format
        run: deno fmt --check

      - name: Run Deno linter
        run: deno lint --unstable
    
      - name: Unit tests
        run: deno test

